import { GoogleGenerativeAI, SchemaType } from "@google/generative-ai";
import type { ResponseSchema } from "@google/generative-ai";

// RENDERING NOTE:
// The returned `html` is a full, self-contained document generated by an LLM.
// Do NOT inject it into the app DOM. On the dashboard, render it inside a
// sandboxed iframe so the markup/styles are isolated from the host page:
//
//   <iframe
//     srcDoc={html}
//     sandbox=""            // empty = most restrictive; add "allow-*" only if needed
//     title="Replicated homepage preview"
//   />
//
// Using `srcDoc` + `sandbox` prevents the generated page from running scripts,
// navigating the top frame, or reaching app cookies/storage. The generation
// prompt forbids external CSS/JS, so an empty sandbox is sufficient.

export type ReplicationBrandTokens = {
  colors: string[];
  font: {
    primary: string | null;
    fallbacks: string[];
  };
  voice: {
    tone: string;
    formality: string;
    phrases: string[];
  };
};

export type ReplicationPage = {
  url: string;
  title: string | null;
  description: string | null;
  headings: {
    h1: string[];
    h2: string[];
  };
  bodyText: string;
};

export type ReplicationFinding = {
  observation: string;
  solution: string;
  principle: string;
  source_book: string;
};

export type ReplicationInput = {
  brandTokens: ReplicationBrandTokens;
  page: ReplicationPage;
  findings: ReplicationFinding[];
};

export type AppliedChange = {
  change: string;
  finding_principle: string;
  source_book: string;
};

export type ReplicatedHomepage = {
  html: string;
  applied_changes: AppliedChange[];
};

type GeminiReplicationModel = {
  generateContent: (prompt: string) => Promise<{
    response: {
      text: () => string;
    };
  }>;
};

const REPLICATION_MODEL = "gemini-2.5-flash";
const BODY_TEXT_LIMIT = 4_000;

const SYSTEM_INSTRUCTION = [
  "You are a conversion rate optimization designer who rebuilds homepages.",
  "You output ONE self-contained HTML document and a list of the changes you applied.",
  "The HTML must render standalone: inline <style> only, no external CSS, JS, fonts, frameworks, or CDN links.",
  "Treat the brand tokens as HARD constraints so the result feels like the source site:",
  "inject the brand colors as CSS custom properties on :root and actually use them (primary color drives the primary CTA);",
  "use the primary font with its fallbacks as the font-family;",
  "write every line of copy in the brand voice (tone and formality), reusing real phrases from the original where natural.",
  "Preserve the spirit and structure of the original: reuse its headings and copy as the base, then improve them per the findings.",
  "This is a recognizable replication, not a site built from scratch.",
  "VISIBLY apply each finding's solution as a concrete element on the page",
  "(e.g. 'add social proof near the CTA' becomes a real testimonial block next to the CTA).",
  "For every change you make, add one applied_changes entry mapping it to the finding's principle and source_book verbatim.",
  "HONESTY: never fabricate specific false claims — no fake statistics and no invented named customers.",
  "Use clearly illustrative placeholders grounded in the original content instead.",
  "Pixel-perfect matching and mobile responsiveness are NOT required; do not over-invest there.",
].join(" ");

const REPLICATION_SCHEMA = {
  type: SchemaType.OBJECT,
  properties: {
    html: {
      type: SchemaType.STRING,
    },
    applied_changes: {
      type: SchemaType.ARRAY,
      items: {
        type: SchemaType.OBJECT,
        properties: {
          change: {
            type: SchemaType.STRING,
          },
          finding_principle: {
            type: SchemaType.STRING,
          },
          source_book: {
            type: SchemaType.STRING,
          },
        },
        required: ["change", "finding_principle", "source_book"],
      },
    },
  },
  required: ["html", "applied_changes"],
} satisfies ResponseSchema;

export async function generateReplicatedHomepage(
  inputs: ReplicationInput,
  options: {
    model?: GeminiReplicationModel;
  } = {},
): Promise<ReplicatedHomepage> {
  const model = options.model ?? createGeminiReplicationModel();
  const prompt = buildReplicationPrompt(inputs);
  let lastError: unknown;

  for (let attempt = 0; attempt < 2; attempt += 1) {
    try {
      const result = await model.generateContent(prompt);
      return parseReplicationJson(result.response.text());
    } catch (error) {
      lastError = error;

      if (!isParseError(error) || attempt === 1) {
        throw new Error(
          `Gemini homepage replication failed: ${errorMessage(error)}`,
        );
      }
    }
  }

  throw new Error(
    `Gemini homepage replication failed after retry: ${errorMessage(lastError)}`,
  );
}

function createGeminiReplicationModel(): GeminiReplicationModel {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    throw new Error("Missing GEMINI_API_KEY environment variable");
  }

  const client = new GoogleGenerativeAI(apiKey);
  const model = client.getGenerativeModel({
    model: REPLICATION_MODEL,
    systemInstruction: SYSTEM_INSTRUCTION,
    generationConfig: {
      temperature: 0.4,
      responseMimeType: "application/json",
      responseSchema: REPLICATION_SCHEMA,
    },
  });

  return {
    generateContent: (prompt: string) => model.generateContent(prompt),
  };
}

function buildReplicationPrompt(inputs: ReplicationInput) {
  return JSON.stringify(
    {
      brandTokens: {
        colors: inputs.brandTokens.colors,
        font: inputs.brandTokens.font,
        voice: inputs.brandTokens.voice,
      },
      page: {
        url: inputs.page.url,
        title: inputs.page.title,
        description: inputs.page.description,
        headings: inputs.page.headings,
        bodyText: inputs.page.bodyText.slice(0, BODY_TEXT_LIMIT),
      },
      findings: inputs.findings.map((finding) => ({
        observation: finding.observation,
        solution: finding.solution,
        principle: finding.principle,
        source_book: finding.source_book,
      })),
    },
    null,
    2,
  );
}

function parseReplicationJson(text: string): ReplicatedHomepage {
  let parsed: unknown;

  try {
    parsed = JSON.parse(text);
  } catch (error) {
    throw new ParseError(
      `Gemini returned invalid replication JSON: ${errorMessage(error)}`,
    );
  }

  if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") {
    throw new Error("Gemini returned malformed replication JSON");
  }

  const record = parsed as Record<string, unknown>;
  const html = record.html;

  if (typeof html !== "string" || html.trim().length === 0) {
    throw new Error("Gemini replication JSON did not include html");
  }

  const appliedChanges = Array.isArray(record.applied_changes)
    ? record.applied_changes
    : null;

  if (!appliedChanges) {
    throw new Error("Gemini replication JSON did not include applied_changes");
  }

  return {
    html: html.trim(),
    applied_changes: appliedChanges.map(validateAppliedChangeRecord),
  };
}

function validateAppliedChangeRecord(value: unknown): AppliedChange {
  if (!value || Array.isArray(value) || typeof value !== "object") {
    throw new Error("Gemini applied change must be an object");
  }

  const record = value as Record<string, unknown>;

  return {
    change: getRequiredString(record, "change"),
    finding_principle: getRequiredString(record, "finding_principle"),
    source_book: getRequiredString(record, "source_book"),
  };
}

function getRequiredString(record: Record<string, unknown>, key: string) {
  const value = record[key];

  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`Gemini applied change is missing valid ${key}`);
  }

  return value.trim();
}

function isParseError(error: unknown) {
  return error instanceof ParseError;
}

class ParseError extends Error {}

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}
